### ISSUE TITLE
IRIC 4.0 - GUI Language - how to set it ?

### ISSUE THREAD

**Issue by jbensabat** [i-RIC/gui_user_manual#10]
Hello 
I have downloaded and installed version 4 of IRIC
after the installation I see that the language of the GUI becomes arabic.
I would like to set it as english 
how can I do that ?
thanks 
jac

**Comment by kskinoue0612** [comment]
Hello. Thank you for the information, and I'm sorry for inconvenience.

Please switch the language in the steps below:

1. Open Preference dialog from the menu below:
![lang_arabic1](https://github.com/i-RIC/gui_user_manual/assets/4031569/a6be36aa-7366-42c7-a322-d23fd7c58985)

2. Switch language from the combo box in the dialog. After changing the language, click the button in the red circle. It is the "OK" button.
![lang_arabic2](https://github.com/i-RIC/gui_user_manual/assets/4031569/6bdb97c9-b9d5-488a-b941-74effad6d7cc)

**Comment by jbensabat** [comment]
Hi 
thanks a lot 
now it I can understand what I see 
best
jac

**Comment by kskinoue0612** [comment]
Thank you for the response.
Glad to hear that your problem is solved.
Thanks,

Keisuke
